export const queries = {
  FETCH_PACKAGE_JSON: 'FETCH_PACKAGE_JSON',
  FETCH_ICON_NODES_JSON: 'FETCH_ICON_NODES_JSON',
  FETCH_TAGS_JSON: 'FETCH_TAGS_JSON',
  FETCH_CATEGORIES_JSON: 'FETCH_CATEGORIES_JSON',
};
